services:
  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - '3998:5432'
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8100
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"

      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: 8100

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
      - --import-realm
    ports:
      - '8100:8100'
    depends_on:
      - postgres
    volumes:
      - keycloak-data:/opt/keycloak/data
      # realm 자동 임포트용
      - ./import/realms:/opt/keycloak/data/import
    networks:
      - keycloak-net
      - gupang-network

volumes:
  postgres-keycloak-data:
  keycloak-data:


networks:
  keycloak-net:
  gupang-network:
    external: true
